sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t klaidigorishti/app.fibonacci-calculator-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run -CI=true klaidigorishti/app.fibonacci-calculator-tests npm test -- --coverage

after_success:
  - docker build -t klaidigorishti/app.fibonacci-calculator-client ./client
  - docker build -t klaidigorishti/app.fibonacci-calculator-nginx ./nginx
  - docker build -t klaidigorishti/app.fibonacci-calculator-server ./server
  - docker build -t klaidigorishti/app.fibonacci-calculator-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  # Push the built images to the Docker Hub
  - docker push  klaidigorishti/app.fibonacci-calculator-client
  - docker push  klaidigorishti/app.fibonacci-calculator-nginx
  - docker push  klaidigorishti/app.fibonacci-calculator-server
  - docker push  klaidigorishti/app.fibonacci-calculator-worker
